import type { CategoryType, PostLocale } from '../components/types'

interface ArticleMessages {
  backToPosts: string
  backToAllPosts: string
  minRead: string
  languageLabel: string
  english: string
  turkish: string
  toc: {
    label: string
    sections: string
    ariaLabel: string
    progressLabel: string
  }
  download: {
    action: string
    downloaded: string
    error: string
  }
  ai: {
    launcher: string
    launcherAria: string
    title: string
    featuresAria: string
    closeAria: string
    disclaimer: string
    tabs: {
      summary: string
      keyPoints: string
      ask: string
      explain: string
    }
    toolbar: {
      stop: string
      regenerate: string
      regenerateAria: string
      copy: string
      copyAria: string
      copied: string
      copyError: string
    }
    error: {
      title: string
      retry: string
    }
    summary: {
      loading: string
      emptyTitle: string
      emptyDescription: string
      action: string
    }
    keyPoints: {
      loading: string
      emptyTitle: string
      emptyDescription: string
      action: string
    }
    explain: {
      loading: string
      emptyTitle: string
      emptyDescription: string
      action: string
    }
    ask: {
      title: string
      description: string
      suggestions: string[]
      placeholder: string
      inputAria: string
      stopAria: string
      sendAria: string
      keyboardHint: string
    }
  }
}

const messages: Record<PostLocale, ArticleMessages> = {
  en: {
    backToPosts: 'Back to posts',
    backToAllPosts: 'Back to all posts',
    minRead: 'min read',
    languageLabel: 'Article language',
    english: 'EN',
    turkish: 'TR',
    toc: {
      label: 'On this page',
      sections: 'sections',
      ariaLabel: 'Table of contents',
      progressLabel: 'Reading progress through sections'
    },
    download: {
      action: 'Download .md',
      downloaded: 'Downloaded!',
      error: 'Failed to download markdown:'
    },
    ai: {
      launcher: 'Ask AI',
      launcherAria: 'Open AI assistant for this article',
      title: 'AI Assistant',
      featuresAria: 'AI toolkit features',
      closeAria: 'Close drawer',
      disclaimer:
        'Answers are generated by AI from this article. They may contain mistakes — verify anything important.',
      tabs: {
        summary: 'Summary',
        keyPoints: 'Key Points',
        ask: 'Ask',
        explain: 'Explain Simply'
      },
      toolbar: {
        stop: 'Stop',
        regenerate: 'Regenerate',
        regenerateAria: 'Regenerate response',
        copy: 'Copy',
        copyAria: 'Copy response',
        copied: 'Copied!',
        copyError: 'Failed to copy AI response:'
      },
      error: {
        title: 'Something went wrong',
        retry: 'Try again'
      },
      summary: {
        loading: 'Summarizing article...',
        emptyTitle: 'No summary yet',
        emptyDescription: 'Generate a quick 4–6 sentence recap of this article.',
        action: 'Summarize'
      },
      keyPoints: {
        loading: 'Extracting key points...',
        emptyTitle: 'No key points yet',
        emptyDescription: 'Extract the important takeaways from this article.',
        action: 'Extract key points'
      },
      explain: {
        loading: 'Rewriting for a junior reader...',
        emptyTitle: 'No explanation yet',
        emptyDescription:
          'Get a junior-friendly rewrite with analogies and jargon defined.',
        action: 'Explain simply'
      },
      ask: {
        title: 'Ask anything about this article',
        description: 'Answers are grounded strictly in the article content.',
        suggestions: [
          'Give me the TL;DR in one sentence.',
          'What problem does this article solve?',
          'Which part should I read first?'
        ],
        placeholder: 'Why are Server Components faster?',
        inputAria: 'Ask a question about the article',
        stopAria: 'Stop generating',
        sendAria: 'Send question',
        keyboardHint: 'Enter to send · Shift+Enter for newline'
      }
    }
  },
  tr: {
    backToPosts: 'Makalelere dön',
    backToAllPosts: 'Tüm makalelere dön',
    minRead: 'dk okuma',
    languageLabel: 'Makale dili',
    english: 'EN',
    turkish: 'TR',
    toc: {
      label: 'Bu sayfada',
      sections: 'bölüm',
      ariaLabel: 'İçindekiler',
      progressLabel: 'Bölümlerdeki okuma ilerlemesi'
    },
    download: {
      action: '.md dosyasını indir',
      downloaded: 'İndirildi!',
      error: 'Markdown indirilemedi:'
    },
    ai: {
      launcher: "AI'a Sor",
      launcherAria: 'Bu makale için AI asistanını aç',
      title: 'AI Asistanı',
      featuresAria: 'AI araçları',
      closeAria: 'Paneli kapat',
      disclaimer:
        'Yanıtlar bu makaleden AI tarafından üretilir. Hata içerebilir; önemli bilgileri doğrulayın.',
      tabs: {
        summary: 'Özet',
        keyPoints: 'Önemli Noktalar',
        ask: 'Sor',
        explain: 'Basitçe Açıkla'
      },
      toolbar: {
        stop: 'Durdur',
        regenerate: 'Yeniden oluştur',
        regenerateAria: 'Yanıtı yeniden oluştur',
        copy: 'Kopyala',
        copyAria: 'Yanıtı kopyala',
        copied: 'Kopyalandı!',
        copyError: 'AI yanıtı kopyalanamadı:'
      },
      error: {
        title: 'Bir sorun oluştu',
        retry: 'Tekrar dene'
      },
      summary: {
        loading: 'Makale özetleniyor...',
        emptyTitle: 'Henüz özet yok',
        emptyDescription: 'Bu makalenin 4–6 cümlelik kısa bir özetini oluşturun.',
        action: 'Özetle'
      },
      keyPoints: {
        loading: 'Önemli noktalar çıkarılıyor...',
        emptyTitle: 'Henüz önemli nokta yok',
        emptyDescription: 'Bu makaledeki önemli çıkarımları belirleyin.',
        action: 'Önemli noktaları çıkar'
      },
      explain: {
        loading: 'Junior okuyucu için yeniden yazılıyor...',
        emptyTitle: 'Henüz açıklama yok',
        emptyDescription:
          "Analojiler ve tanımlanmış teknik terimlerle junior developer'a uygun bir anlatım oluşturun.",
        action: 'Basitçe açıkla'
      },
      ask: {
        title: 'Bu makale hakkında istediğinizi sorun',
        description: 'Yanıtlar yalnızca makalenin içeriğine dayanır.',
        suggestions: [
          "Tek cümlelik TL;DR'ı nedir?",
          'Bu makale hangi problemi çözüyor?',
          'Önce hangi bölümü okumalıyım?'
        ],
        placeholder: 'Server Components neden daha hızlıdır?',
        inputAria: 'Makale hakkında soru sor',
        stopAria: 'Yanıt oluşturmayı durdur',
        sendAria: 'Soruyu gönder',
        keyboardHint: 'Göndermek için Enter · Yeni satır için Shift+Enter'
      }
    }
  }
}

const categoryLabels: Record<PostLocale, Record<CategoryType, string>> = {
  en: {
    'Artificial Intelligence': 'Artificial Intelligence',
    ReactJS: 'ReactJS',
    NextJS: 'NextJS',
    TypeScript: 'TypeScript',
    JavaScript: 'JavaScript',
    CSS: 'CSS',
    TailwindCSS: 'TailwindCSS',
    HTML: 'HTML',
    'Self-improvement': 'Self-improvement'
  },
  tr: {
    'Artificial Intelligence': 'Yapay Zekâ',
    ReactJS: 'ReactJS',
    NextJS: 'NextJS',
    TypeScript: 'TypeScript',
    JavaScript: 'JavaScript',
    CSS: 'CSS',
    TailwindCSS: 'TailwindCSS',
    HTML: 'HTML',
    'Self-improvement': 'Kişisel Gelişim'
  }
}

export const POST_LOCALE_CONFIG: Record<
  PostLocale,
  {
    languageTag: string
    openGraphLocale: string
  }
> = {
  en: {
    languageTag: 'en-US',
    openGraphLocale: 'en_US'
  },
  tr: {
    languageTag: 'tr-TR',
    openGraphLocale: 'tr_TR'
  }
}

export const getPostPath = (slug: string, locale: PostLocale): string =>
  locale === 'en' ? `/posts/${slug}` : `/tr/posts/${slug}`

export const getArticleMessages = (locale: PostLocale): ArticleMessages =>
  messages[locale]

export const getCategoryLabel = (
  category: CategoryType,
  locale: PostLocale
): string => categoryLabels[locale][category]

